Javascript 5
kumite73/kiselev-aleksei-otus pull request #6
Opened 2018-11-22 13:18 UTC by kumite73

Результат работы
```javascript
Генерируем число для rs:  Шаг + 1 74
Генерируем число для rs:  Шаг + 2 75
Генерируем число для rs:  Шаг + 3 76
Получаем из rs:  74
Генерируем добавочное число:  65
Пришло из потока ts:  139
Получаем из rs:  75
Генерируем добавочное число:  41
Пришло из потока ts:  116
Получаем из rs:  76
Генерируем добавочное число:  82
Пришло из потока ts:  158
```

2018-11-24 14:04 UTC, thoughtspile requested changes

2018-11-24 14:04 UTC, thoughtspile commented on javascript-5/stream.js
> +  let rnd = parseInt((Math.random() * 100), 10);
Если `parseInt` для округления, то лучше не надо. Зачем преобразовывать число -> строка -> число, когда можно просто `Math.floor`?

2018-11-24 14:04 UTC, thoughtspile commented on javascript-5/stream.js
> +rs._read = () => {
Не стоит создавать объекты, а потом переопределять их методы. Есть 2 способа сделать это аккуратнее:
1. Опция `{ read: ... }` в конструкторе
2. Подкласс: `RandomEmitter extends Readable { _read() ... }`

2018-11-24 14:04 UTC, thoughtspile commented on javascript-5/stream.js
> +const clog = console.log;
Я все еще не понимаю, зачем это

2018-11-24 16:42 UTC, kumite73 commented on javascript-5/stream.js
> +const clog = console.log;
Просто быстрее и удобнее отлаживать :) Их пока 100 штук напишешь,, даже с подстановкой ... упаришься :)

2018-11-24 17:46 UTC, kumite73 commented on javascript-5/stream.js
> +rs._read = () => {
Переписал на вариант номер 2. Первый даже не понял, как гуглить....

2018-11-24 17:46 UTC, kumite73 commented on javascript-5/stream.js
> +  let rnd = parseInt((Math.random() * 100), 10);
Fix

2018-11-26 11:02 UTC, thoughtspile commented on javascript-5/stream.js
> +rs._read = () => {
Почему не стоит делать `new Class`, а потом переопределять методы руками (это называется [monkey-patching](https://ru.wikipedia.org/wiki/Monkey_patch)), думаю, понятно — потому что один метод общепринятый и прямой, а другой — костыльный. Кроме того, если использовать стрелочные функции для методов, в них `this` будет тем же, что в точке объявления метода — это или `undefined`, или `window` (не спрашивайте почему). Есть [ситуации](https://medium.com/komenco/react-autobinding-2261a1092849), в которых нормально объявлять методы стрелками внутри конструктора — так `this` намертво привяжется к конкретному экземпляру объекта.

Первый вариант можно посмотреть в [документации на Stream API](https://nodejs.org/api/stream.html#stream_simplified_construction). Конструктор `Stream` принимает аргумент с опциями (вы заметили), и среди опций есть реализации `read / write / transform`.

2018-11-26 11:04 UTC, thoughtspile requested changes

2018-11-26 11:04 UTC, thoughtspile commented on javascript-5/stream.js
> +      rs.push(rnd + 1);
как нехорошо, нужно же наверное привязываться к тому экземпляру который мы создаем (`this`), а не какой-то переменной из родительской области видимости!

2018-11-26 11:05 UTC, thoughtspile requested changes

2018-11-26 11:05 UTC, thoughtspile commented on javascript-5/stream.js
> +    this._write = (chunk, enc, next) => {
ну и можно просто объявить `_write` как метод (не в конструкторе)

2018-11-26 12:36 UTC, kumite73 commented on javascript-5/stream.js
> +      rs.push(rnd + 1);
И правда нехорошо :)

2018-11-26 12:37 UTC, kumite73 commented on javascript-5/stream.js
> +    this._write = (chunk, enc, next) => {
Переписал

2018-12-02 19:00 UTC, merged